use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result, bail};

use heck::{ToSnakeCase, ToUpperCamelCase};

use ron::value::Value as RonValue;

use crate::model::{CppSpec, Ty};
use crate::parse::{
    enum_case, expect_bool, expect_integer, expect_number, expect_rotator, expect_string,
    expect_vector, sanitize_field_name, sanitize_type_name,
};

/// Generate a single Rust file (e.g., rebase_generated.rs) that contains all generated
/// modules, enums, structs, data, and helper functions derived from the provided specs.
///
/// The generator groups types by their namespace_chain and opens each namespace only once,
/// placing all of that group's type modules inside it. This prevents duplicate module
/// declarations when multiple types share the same namespace.
///
/// - `specs`: normalized data specifications collected from the RON inputs
/// - `out_file`: path to the output Rust file (e.g., target/rebase_generated.rs)
/// - `force`: if false and file exists, generation will fail; if true, file is overwritten
///
/// Returns a human-readable description (the output file name).
pub fn generate_rust_single_file(
    specs: &[CppSpec],
    out_file: &Path,
    force: bool,
) -> Result<String> {
    if out_file.exists() && !force {
        bail!(
            "Refusing to overwrite existing file: {}",
            out_file.display()
        );
    }

    // Group specs by namespace chain (joined with ::)
    let mut groups: BTreeMap<String, Vec<&CppSpec>> = BTreeMap::new();
    for spec in specs {
        let key = if spec.namespace_chain.is_empty() {
            String::new()
        } else {
            spec.namespace_chain.join("::")
        };
        groups.entry(key).or_default().push(spec);
    }

    let mut content = String::new();
    // Plain banner comment to avoid doc/attr ordering issues when included anywhere.
    writeln!(&mut content, "// AUTOGENERATED by ReBase. DO NOT EDIT.")?;
    writeln!(&mut content)?;

    for (ns_key, group_specs) in groups {
        // Open namespace modules if any
        let mut ns_count = 0usize;
        if !ns_key.is_empty() {
            for ns in ns_key.split("::") {
                writeln!(&mut content, "pub mod {} {{", ns.to_snake_case())?;
                ns_count += 1;
            }
        }

        // Emit each type module inside the namespace
        for spec in group_specs {
            let block = render_type_module_inner(spec)?;
            content.push_str(&block);
            content.push('\n');
        }

        // Close namespaces
        for _ in 0..ns_count {
            writeln!(&mut content, "}} // namespace")?;
        }
        if ns_count > 0 {
            content.push('\n');
        }
    }

    fs::write(out_file, content)
        .with_context(|| format!("Failed to write {}", out_file.display()))?;

    Ok(out_file
        .file_name()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_else(|| "rebase_generated.rs".to_string()))
}

/// Render a single type's Rust module without opening or closing namespace modules.
/// The resulting block contains:
/// - Enums (if any)
/// - Helper types (Vector/Rotator) as needed by fields
/// - Row struct
/// - Static dataset
/// - get_<type>_data() and find_<type>_by_name() APIs
fn render_type_module_inner(spec: &CppSpec) -> Result<String> {
    let mut s = String::new();

    let mod_name = sanitize_type_name(&spec.type_name).to_snake_case();
    let row_name = format!("{}Row", sanitize_type_name(&spec.type_name));
    let static_name = format!("{}_DATA", sanitize_type_name(&spec.type_name)).to_uppercase();
    let get_fn = format!("get_{}_data", mod_name);
    let find_fn = format!("find_{}_by_name", mod_name);

    writeln!(&mut s, "pub mod {} {{", mod_name)?;

    // Enums
    for e in &spec.enums {
        writeln!(
            &mut s,
            "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub enum {} {{",
            sanitize_type_name(&e.name)
        )?;
        for v in &e.values {
            writeln!(&mut s, "    {},", enum_case(v))?;
        }
        writeln!(&mut s, "}}\n")?;
    }

    // Helper types
    if spec
        .fields
        .iter()
        .any(|f| matches!(f.ty, crate::model::Ty::Vector))
    {
        writeln!(
            &mut s,
            "#[derive(Debug, Clone, Copy, PartialEq)]\npub struct Vector {{ pub x: f32, pub y: f32, pub z: f32 }}\n"
        )?;
    }
    if spec
        .fields
        .iter()
        .any(|f| matches!(f.ty, crate::model::Ty::Rotator))
    {
        writeln!(
            &mut s,
            "#[derive(Debug, Clone, Copy, PartialEq)]\npub struct Rotator {{ pub pitch: f32, pub yaw: f32, pub roll: f32 }}\n"
        )?;
    }

    // Row struct
    writeln!(&mut s, "#[derive(Debug, Clone)]")?;
    writeln!(&mut s, "pub struct {} {{", row_name)?;
    writeln!(&mut s, "    pub name: &'static str,")?;
    for f in &spec.fields {
        let rs = rust_type_for(&f.ty);
        writeln!(
            &mut s,
            "    pub {}: {},",
            sanitize_field_name(&f.name).to_snake_case(),
            rs
        )?;
    }
    writeln!(&mut s, "}}\n")?;

    // Static data
    writeln!(&mut s, "pub static {}: &[{}] = &[", static_name, row_name)?;
    for r in &spec.records {
        writeln!(&mut s, "    {} {{", row_name)?;
        writeln!(&mut s, "        name: \"{}\",", escape_rust_string(&r.name))?;
        for f in &spec.fields {
            let v = r.values.get(&f.name).expect("validated earlier");
            let expr = rust_expr_for_value(v, &f.ty)?;
            writeln!(
                &mut s,
                "        {}: {},",
                sanitize_field_name(&f.name).to_snake_case(),
                expr
            )?;
        }
        writeln!(&mut s, "    }},")?;
    }
    writeln!(&mut s, "];\n")?;

    // API
    writeln!(
        &mut s,
        "pub fn {}() -> &'static [{}] {{ {} }}",
        get_fn, row_name, static_name
    )?;
    writeln!(
        &mut s,
        "pub fn {}(name: &str) -> Option<&'static {}> {{",
        find_fn, row_name
    )?;
    writeln!(
        &mut s,
        "    {}.iter().find(|r| r.name == name)",
        static_name
    )?;
    writeln!(&mut s, "}}\n")?;

    writeln!(&mut s, "}} // mod {}", mod_name)?;

    Ok(s)
}

/// Map normalized type to Rust type.
fn rust_type_for(ty: &Ty) -> String {
    match ty {
        Ty::String | Ty::FName => "&'static str".into(),
        Ty::Float => "f32".into(),
        Ty::Double => "f64".into(),
        Ty::Int32 => "i32".into(),
        Ty::Bool => "bool".into(),
        Ty::Vector => "Vector".into(),
        Ty::Rotator => "Rotator".into(),
        Ty::Enum { name } => sanitize_type_name(name),
    }
}

/// Render a Rust expression for a RonValue based on the target type.
fn rust_expr_for_value(v: &RonValue, ty: &Ty) -> Result<String> {
    Ok(match ty {
        Ty::String | Ty::FName => {
            format!("\"{}\"", escape_rust_string(expect_string(v)?))
        }
        Ty::Float => {
            let f = expect_number(v)? as f32;
            format!("{:?}", f)
        }
        Ty::Double => {
            let d = expect_number(v)?;
            format!("{:?}", d)
        }
        Ty::Int32 => {
            let i = expect_integer(v)?;
            if i < i32::MIN as i64 || i > i32::MAX as i64 {
                bail!("integer {} out of i32 range", i);
            }
            format!("{}", i as i32)
        }
        Ty::Bool => format!("{}", expect_bool(v)?),
        Ty::Vector => {
            let (x, y, z) = expect_vector(v)?;
            format!("Vector {{ x: {:?}, y: {:?}, z: {:?} }}", x, y, z)
        }
        Ty::Rotator => {
            let (p, y, r) = expect_rotator(v)?;
            format!("Rotator {{ pitch: {:?}, yaw: {:?}, roll: {:?} }}", p, y, r)
        }
        Ty::Enum { name } => {
            let s = expect_string(v)?;
            format!("{}::{}", sanitize_type_name(name), enum_case(s))
        }
    })
}

/// Escape a string for safe embedding in Rust source code.
fn escape_rust_string(s: &str) -> String {
    s.chars()
        .flat_map(|ch| match ch {
            '\\' => "\\\\".chars().collect::<Vec<_>>(),
            '\"' => "\\\"".chars().collect::<Vec<_>>(),
            '\n' => "\\n".chars().collect::<Vec<_>>(),
            '\r' => "\\r".chars().collect::<Vec<_>>(),
            '\t' => "\\t".chars().collect::<Vec<_>>(),
            c => [c].to_vec(),
        })
        .collect()
}
