use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result, anyhow, bail};
use ron::value::Value as RonValue;

use crate::model::{CppSpec, EnumDef, Ty};
use crate::parse::{
    enum_case, expect_bool, expect_integer, expect_number, expect_rotator, expect_string,
    expect_vector, quote_text_literal, sanitize_field_name, sanitize_type_name,
};

/// Generate UE5 C++ header/source files for a given type specification.
///
/// Writes two files into `out_dir`:
/// - `<TypeName>ReBase.h`
/// - `<TypeName>ReBase.cpp`
///
/// Returns a human-readable summary string of generated files.
pub fn generate_cpp_files(spec: &CppSpec, out_dir: &Path, force: bool) -> Result<String> {
    let base = format!("{}ReBase", sanitize_type_name(&spec.type_name));
    let header_name = format!("{base}.h");
    let source_name = format!("{base}.cpp");

    let header_path = out_dir.join(&header_name);
    let source_path = out_dir.join(&source_name);

    if !force {
        if header_path.exists() {
            bail!(
                "Refusing to overwrite existing file: {}",
                header_path.display()
            );
        }
        if source_path.exists() {
            bail!(
                "Refusing to overwrite existing file: {}",
                source_path.display()
            );
        }
    }

    let header = render_header(spec, &header_name)?;
    let source = render_source(spec, &header_name)?;

    fs::write(&header_path, header)
        .with_context(|| format!("Failed writing {}", header_path.display()))?;
    fs::write(&source_path, source)
        .with_context(|| format!("Failed writing {}", source_path.display()))?;

    Ok(format!(
        "{} -> [{}, {}]",
        spec.type_name,
        header_path.file_name().unwrap().to_string_lossy(),
        source_path.file_name().unwrap().to_string_lossy()
    ))
}

fn render_header(spec: &CppSpec, header_name: &str) -> Result<String> {
    let mut s = String::new();
    writeln!(&mut s, "/// AUTOGENERATED by ReBase. DO NOT EDIT.")?;
    writeln!(&mut s, "// Source: data-driven RON")?;
    writeln!(&mut s, "#pragma once")?;
    writeln!(&mut s)?;
    writeln!(&mut s, "#include \"CoreMinimal.h\"")?;
    writeln!(&mut s)?;

    // namespace open
    for ns in &spec.namespace_chain {
        writeln!(&mut s, "namespace {} {{", ns)?;
    }

    // Enums
    if !spec.enums.is_empty() {
        for e in &spec.enums {
            writeln!(
                &mut s,
                "enum class E{} : uint8 {{",
                sanitize_type_name(&e.name)
            )?;
            for (i, v) in e.values.iter().enumerate() {
                let en = enum_case(v);
                if i + 1 == e.values.len() {
                    writeln!(&mut s, "    {}", en)?;
                } else {
                    writeln!(&mut s, "    {},", en)?;
                }
            }
            writeln!(&mut s, "}};")?;
            writeln!(&mut s)?;
        }
    }

    // Row struct
    writeln!(
        &mut s,
        "struct F{}Row {{",
        sanitize_type_name(&spec.type_name)
    )?;
    writeln!(&mut s, "    // Primary record name (from RON 'name')")?;
    writeln!(&mut s, "    FString Name;")?;
    for f in &spec.fields {
        if let Some(doc) = &f.doc {
            for line in doc.lines() {
                writeln!(&mut s, "    // {}", line.trim())?;
            }
        }
        writeln!(
            &mut s,
            "    {} {};",
            f.cpp_type,
            sanitize_field_name(&f.name)
        )?;
    }
    writeln!(&mut s, "}};")?;
    writeln!(&mut s)?;

    // API
    writeln!(
        &mut s,
        "const TArray<F{}Row>& Get{}Data();",
        sanitize_type_name(&spec.type_name),
        sanitize_type_name(&spec.type_name)
    )?;
    writeln!(
        &mut s,
        "const F{}Row* Find{}ByName(FStringView Name);",
        sanitize_type_name(&spec.type_name),
        sanitize_type_name(&spec.type_name)
    )?;

    // namespace close
    for _ in &spec.namespace_chain {
        writeln!(&mut s, "}} // namespace")?;
    }

    writeln!(&mut s, "// End of file")?;
    Ok(s)
}

fn render_source(spec: &CppSpec, header_name: &str) -> Result<String> {
    let mut s = String::new();
    writeln!(&mut s, "/// AUTOGENERATED by ReBase. DO NOT EDIT.")?;
    writeln!(&mut s, "#include \"{}\"", header_name)?;
    writeln!(&mut s)?;

    // namespace open
    for ns in &spec.namespace_chain {
        writeln!(&mut s, "namespace {} {{", ns)?;
    }

    // Data initializer
    let init_fn = format!("Init{}Data", sanitize_type_name(&spec.type_name));
    writeln!(
        &mut s,
        "static void {}(TArray<F{}Row>& Out)",
        init_fn,
        sanitize_type_name(&spec.type_name)
    )?;
    writeln!(&mut s, "{{")?;
    writeln!(&mut s, "    Out.Reserve({});", spec.records.len())?;

    for r in &spec.records {
        writeln!(
            &mut s,
            "    Out.Add(F{}Row{{",
            sanitize_type_name(&spec.type_name)
        )?;
        // Name first
        writeln!(&mut s, "        TEXT({}),", quote_text_literal(&r.name))?;
        // fields
        for (i, f) in spec.fields.iter().enumerate() {
            let v = r.values.get(&f.name).expect("validated earlier");
            let expr = cpp_expr_for_value(v, &f.ty, &spec.enums)
                .with_context(|| format!("Record '{}' field '{}'", r.name, f.name))?;
            let suffix = if i + 1 == spec.fields.len() { "" } else { "," };
            writeln!(&mut s, "        {}{}", expr, suffix)?;
        }
        writeln!(&mut s, "    }});")?;
    }

    writeln!(&mut s, "}}")?;
    writeln!(&mut s)?;

    // Get function
    writeln!(
        &mut s,
        "const TArray<F{}Row>& Get{}Data() {{",
        sanitize_type_name(&spec.type_name),
        sanitize_type_name(&spec.type_name)
    )?;
    writeln!(
        &mut s,
        "    static TArray<F{}Row> Data;",
        sanitize_type_name(&spec.type_name)
    )?;
    writeln!(&mut s, "    if (Data.Num() == 0) {{")?;
    writeln!(&mut s, "        {}(Data);", init_fn)?;
    writeln!(&mut s, "    }}")?;
    writeln!(&mut s, "    return Data;")?;
    writeln!(&mut s, "}}")?;
    writeln!(&mut s)?;

    // Find function
    writeln!(
        &mut s,
        "const F{}Row* Find{}ByName(FStringView Name) {{",
        sanitize_type_name(&spec.type_name),
        sanitize_type_name(&spec.type_name)
    )?;
    writeln!(
        &mut s,
        "    const TArray<F{}Row>& Data = Get{}Data();",
        sanitize_type_name(&spec.type_name),
        sanitize_type_name(&spec.type_name)
    )?;
    writeln!(
        &mut s,
        "    for (const F{}Row& Row : Data) {{",
        sanitize_type_name(&spec.type_name)
    )?;
    writeln!(
        &mut s,
        "        if (Row.Name.Equals(FString(Name))) {{ return &Row; }}"
    )?;
    writeln!(&mut s, "    }}")?;
    writeln!(&mut s, "    return nullptr;")?;
    writeln!(&mut s, "}}")?;

    // namespace close
    for _ in &spec.namespace_chain {
        writeln!(&mut s, "}} // namespace")?;
    }

    writeln!(&mut s, "// End of file")?;
    Ok(s)
}

fn cpp_expr_for_value(v: &RonValue, ty: &Ty, enums: &[EnumDef]) -> Result<String> {
    Ok(match ty {
        Ty::String => format!("FString(TEXT({}))", quote_text_literal(expect_string(v)?)),
        Ty::FName => format!("FName(TEXT({}))", quote_text_literal(expect_string(v)?)),
        Ty::Float => {
            let f = expect_number(v)? as f32;
            if f.is_finite() {
                format!("{:.6}f", f)
            } else if f.is_infinite() && f.is_sign_positive() {
                "INFINITY".to_string()
            } else if f.is_infinite() && f.is_sign_negative() {
                "-INFINITY".to_string()
            } else {
                "NAN".to_string()
            }
        }
        Ty::Double => {
            let d = expect_number(v)?;
            if d.is_finite() {
                format!("{:.12}", d)
            } else if d.is_infinite() && d.is_sign_positive() {
                "INFINITY".to_string()
            } else if d.is_infinite() && d.is_sign_negative() {
                "-INFINITY".to_string()
            } else {
                "NAN".to_string()
            }
        }
        Ty::Int32 => {
            let i = expect_integer(v)?;
            if i < i32::MIN as i64 || i > i32::MAX as i64 {
                bail!("integer {} out of int32 range", i);
            }
            format!("{}", i as i32)
        }
        Ty::Bool => format!("{}", expect_bool(v)?),
        Ty::Vector => {
            let (x, y, z) = expect_vector(v)?;
            format!("FVector({:.6}f, {:.6}f, {:.6}f)", x, y, z)
        }
        Ty::Rotator => {
            let (p, y, r) = expect_rotator(v)?;
            format!("FRotator({:.6}f, {:.6}f, {:.6}f)", p, y, r)
        }
        Ty::Enum { name } => {
            let s = expect_string(v)?;
            let def = enums
                .iter()
                .find(|e| &e.name == name)
                .ok_or_else(|| anyhow!("enum {} not found in spec generation", name))?;
            let en = enum_case(s);
            if !def.values.iter().any(|v| enum_case(v) == en) {
                bail!(
                    "enum value '{}' not declared for Enum({}), known: {:?}",
                    s,
                    name,
                    def.values
                );
            }
            format!("E{}::{}", sanitize_type_name(name), en)
        }
    })
}
